code: G3ELVB
content_warnings: null
description: "<p>What really makes a startup succeed? It’s not just product-market\
  \ fit or clever tech—it’s the people and the culture they create together. In this\
  \ talk, I’ll share lessons from my journey across three startups at different stages,\
  \ through acquisitions, pivots, and cultural transformations.</p>\n<p>I’ll explore\
  \ the core values that I’ve seen make the biggest difference—not the ones painted\
  \ on walls, but the ones that show up in code reviews, standups, hard conversations,\
  \ and late-night problem solving. We’ll talk about:<br />\n    •   Authenticity\
  \ over performance<br />\n    •   Love and empathy as engineering virtues<br />\n\
  \    •   Presence and trust in high-stakes uncertainty<br />\n    •   Balance, sustainability,\
  \ and knowing when to push or pause<br />\n    •   Grit, growth, and intentionality—what\
  \ it really takes to build something that lasts</p>\n<p>This talk is for anyone\
  \ who wants to build or be part of a values-driven team: engineers, tech leads,\
  \ future founders, or just curious humans trying to build things that matter.</p>"
discord_channel_id: ''
duration: 30
end_time: '2025-07-26T14:45:00-04:00'
qna: false
qna_channel: null
room: Ballroom B
slug: the-core-values-of-a-successful-startup
speakers:
- avatar: https://pretalx.com/media/avatars/XCB3TE_xnPYOhl.jpeg
  code: XCB3TE
  name: Daniel Kim
  slug: daniel-kim
start_time: '2025-07-26T14:15:00-04:00'
stream_timestamp: ''
title: The Core Values of a Successful Startup
type: 30 Minute Talk
youtube_url: null
