backend:
  name: github
  repo: pyohio/pyohio-static-website
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "general-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "general-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/sponsorship/index.md"
        label: "Sponsorship Prospectus"
        name: "sponsorship"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "general-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/keep-in-touch/index.md"
        label: "Keep In Touch"
        name: "keep-in-touch"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "general-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "sponsors"
    label: "Sponsors"
    folder: "data/sponsors"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "URL", name: "url", widget: ""}
      - {label: "Description", name: "description", widget: "text"}
      # - label: "Sponsor Level"
      #   name: "level"
      #   widget: "relation"
      #   collection: "sponsor-levels"
      #   searchFields: ["name"]
      #   valueField: "name"
      #   displayFields: ["name", "amount"]
  # - name: "data"
  #   label: "Data"
  #   files:
  #     - name: "sponsor-levels"
  #       label: "Sponsor Levels"
  #       file: "src/data/sponsor-levels.yml"
  #       create: true
  #       fields:
  #         - {label: Title, name: title, widget: string}
  #         - label: "Levels"
  #           name: "levels"
  #           widget: "list"
  #           fields:
  #             - {label: Name, name: name, widget: string}
  #             - {label: Amount, name: amount, widget: number}