code: RXXMJE
content_warnings: null
description: "<p>OpenSearch, a community-driven, open-source project, offers a robust
  alternative for search and analytics needs. When coupled with Python's flexibility
  and the efficiency of serverless architecture, it transforms into a dynamic trio
  that empowers developers to create efficient and modern search applications.</p>

  <p>Join us on a journey as we explore the synergy between OpenSearch, Python, and
  serverless architecture. In this talk, we'll provide an overview of OpenSearch
  and demonstrate how to utilize Python with serverless architecture to power your
  search engine. Additionally, we will delve into best practices and challenges that
  arise when employing this combination in production.</p>

  <p>By the end of this talk, you'll gain a clear understanding of how to architect,
  build, and deploy efficient search applications using OpenSearch, Python, and serverless
  architecture. Whether you're a developer aiming to enhance your search capabilities
  or an architect exploring modern search solutions, this talk will equip you with
  the tools and insights needed to embrace this exciting synergy.</p>"
discord_channel_id: ''
duration: 15
end_time: TBD
qna: true
qna_channel: exploring-opensearch-python-and-serverless
slug: exploring-opensearch-python-and-serverless
speakers:
  - avatar: https://pretalx.com/media/avatars/Screenshot_2023-10-23_at_13.58.21_ASc9dXP.png
    code: Z8HXML
    name: Yuliia Barabash, Laysa Uchoa
    slug: yuliia-barabash-laysa-uchoa
start_time: TBD
stream_timestamp: ''
title: 'Exploring OpenSearch, Python, and Serverless: Crafting Efficient and Modern
  Search Applications'
type: Short Talk
youtube_url: null
