code: YAQZHH
content_warnings: null
description: '<p>With an average of 195 daily deaths due to synthetic opioids overdose
  in 2021, the US have been facing an unprecedented opioids crisis. Fentanyl and its
  analogues have been a major source of concern, due to their high levels of addiction,
  fast-acting mechanisms, and detection challenges. Fast, effective, and accurate
  identification and quantification of fentanyl, its analogues, and metabolites are
  essential to help prevent overdose-related incidents and to enable agile medical
  response. Although electrochemical sensors represent a promising technology for
  selectively detecting opioids at low concentrations, analyzing and processing the
  data remains one of the major challenges. To tackle this challenge, certain Python
  libraries, such as <em>scipy.signal</em>, could be useful in processing signals
  with high levels of noise and interference from other substances. </p>

  <p>This talk will focus on specific examples of how such libraries could help enable
  filtering, Fourier transformation, and wavelet analysis of electrochemical data.
  As examples, code snippets and outputs will be shown to demonstrate how Python can
  help improve the quality and usability of electrochemical data. Additionally, this
  talk will show how data processing can further benefit from hyper parameter optimization
  techniques, enabled by libraries like <em>hyperopt</em> and <em>ray-tune</em>. By
  doing so, my hope is to demonstrate how Python could be extremely useful in helping
  address problems at the intersection of statistics, public health, and public policy.</p>'
discord_channel_id: ''
duration: 30
end_time: '2024-07-28T13:00:00-04:00'
qna: false
qna_channel: null
room: Orchid Ballroom West
slug: signal-processing-in-electrochemistry-with-python-applications
speakers:
- avatar: https://pretalx.com/media/avatars/UYRBHX_gusMbKM.png
  code: UYRBHX
  name: Rodrigo Silva Ferreira
  slug: rodrigo-silva-ferreira
start_time: '2024-07-28T12:30:00-04:00'
stream_timestamp: ''
title: 'Signal Processing in Electrochemistry with Python: Applications to the US
  Opioids Crisis'
type: 30 Minute Talk
youtube_url: null
